/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    // JAX-RS spec
    implementation("jakarta.ws.rs:jakarta.ws.rs-api:2.1.6")
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:2.3.2")

    // CXF implementation of JAX RS
    implementation("org.apache.cxf:cxf-rt-frontend-jaxrs:3.5.0")
    implementation("org.apache.cxf:cxf-rt-transports-http-jetty:3.5.0")

    // Logging
    implementation("org.slf4j:slf4j-api:1.7.2")
    implementation("ch.qos.logback:logback-core:1.0.9")
    implementation("ch.qos.logback:logback-classic:1.0.9")
}

application {
    // Define the main class for the application.
    mainClass.set("jaxrs.cxf.App")
    applicationDefaultJvmArgs = listOf("-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Slf4jLogger")
}
